# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
jobs:
  build:
    docker:
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: python:3.7.3-stretch

    working_directory: ~/project-repo

    steps:
      - checkout

      - restore_cache:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ./venv

      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
